### ISSUE TITLE
Change the minimum version requirements or disable the 'GPUShaderCreateInfo' call on versions below 3.4

### ISSUE THREAD

**Issue by Oxicid** [JulienHeijmans/quicksnap#53]
Modules Installed (quicksnap-1_4_2) from 'C:\\Users\\Oxicid\\Downloads\\quicksnap-1_4_2.zip' into 'C:\\Users\\Oxicid\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender\blender-3.0.0-beta+v30.ab7214ca2ef9-windows.amd64-release\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Oxicid\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\quicksnap-1_4_2\__init__.py", line 31, in <module>
    globals()[currentModuleFullName] = importlib.import_module(currentModuleFullName)
  File "C:\Program Files\Blender\blender-3.0.0-beta+v30.ab7214ca2ef9-windows.amd64-release\3.0\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Oxicid\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\quicksnap-1_4_2\quicksnap_render.py", line 29, in <module>
    shader_2d_image_info = gpu.types.GPUShaderCreateInfo()
AttributeError: module 'gpu.types' has no attribute 'GPUShaderCreateInfo'

**Comment by Oxicid** [comment]
But most likely such code would be harder to maintain, it's just that you have meaningless conditional expressions in your code (if bpy.app.version >= (3, 4, 0)), everything breaks at the stage of calling gpu.types.GPUShaderCreateInfo()

**Comment by JulienHeijmans** [comment]
What version are you using? The `bpy.app.version >= (3, 4, 0)` seemed to work during my tests.

**Comment by JulienHeijmans** [comment]
Can you try using the latest trunk?

**Comment by Oxicid** [comment]
I made a mistake, the addon worked in version 3.2, it did not work in version 3.1 and below.

Now everything works in versions: 3.0, 3.1, 3.2, 3.5.

Perhaps this was not necessary to do, but I think it's too early to give up version 3.1, 3.0 (and 2.9???)


Another very minor point, totally unimportant
When I pressed LMB and snapped to the object with the modifier, nothing happens when I press the "M" button (only the display of vertexes and edgies changes). 
Ctrl+Shift+V -> M -> LMB - Work
Ctrl+Shift+V -> LMB -> M - Not work
But it saves the state of the properties and if you call like this, everything works, 
Ctrl+Shift+V -> LMB -> M -> Esc -> Ctrl+Shift+V -> LMB - Work

This will just confuse some users, but then again it's not even close to being a big deal.
